### ISSUE TITLE
Fix typo and grammatical errors

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tfcmt-docs#215]
We check typo with typos in CI, but maybe we miss any typo.

https://github.com/suzuki-shunsuke/tfcmt-docs/blob/f71bc171bc56451b1611426bb026e49d91ce2365/.github/workflows/test.yaml#L139-L149

And I'm not so good at English, so there may be some grammatical errors in the document.

**Comment by prashant226** [comment]
please assign this to me

**Comment by suzuki-shunsuke** [comment]
Thank you for your contribution!
Let me add the description same with https://github.com/aquaproj/aquaproj.github.io/issues/565#issuecomment-1741955921 .

This issue means if you find any typos and grammatical errors in the document, please correct them.

**Comment by suzuki-shunsuke** [comment]
@Vishusingh16 Thank you!

@prashant226 Are you still working on it? If so, which pages are you working on?

I think you guys can work together by separating pages.

**Comment by suzuki-shunsuke** [comment]
I close this issue because this is inactive.
If you find any typo or grammatical errors, please send pull requests!
